# BigDataSchool.in

### SriSreedhar

In [1]:
import numpy as np

In [2]:
pyl=[2,3,4,5,6,7,8,9]
# add 100 to every number, append them to a new list

In [3]:
newlist=[]

In [4]:
for eachone in pyl:
    newlist.append(eachone+100)

In [5]:
newlist

[102, 103, 104, 105, 106, 107, 108, 109]

In [6]:
npl=np.array(pyl)

In [8]:
type(npl)

numpy.ndarray

In [9]:
npl

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
npl+100

array([102, 103, 104, 105, 106, 107, 108, 109])

In [11]:
# Numpy - Array
# python - List

In [13]:
# create an arryain numpy
# np.array() -> pass a python list into it

In [14]:
r1=[1,2,3,4]
r2=[5,6,7,8]
r3=[9,10,11,12]
r4=[13,14,15,16]

In [15]:
# single array

In [16]:
m=np.array([
    r1,r2,r3,r4
])

In [17]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# array.shape -> (rows,cols)

In [18]:
m.shape

(4, 4)

In [19]:
npl.shape

(8,)

In [ ]:
# number of values in an array
# array.size

In [20]:
m.size

16

In [22]:
# data types of a array
# array.dtype

In [23]:
m.dtype

dtype('int32')